version: '3'
services:
  #PHP Service
  shoes_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shoes/shoes.vn
    container_name: shoes_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: shoes_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - shoes-network

  #Nginx Service
  shoes_webserver:
    image: nginx:alpine
    container_name: shoes_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "2218:80"
      - "2219:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - shoes-network

  #MySQL Service
  shoes_db:
    image: mysql:5.7.22
    container_name: shoes_db
    restart: unless-stopped
    tty: true
    ports:
      - "63306:3306"
    environment:
      MYSQL_DATABASE: shoes.vn
      MYSQL_ROOT_PASSWORD: Admin@123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - shoes-network

#Volumes
volumes:
  dbdata:
    driver: local

#Docker Networks
networks:
  shoes-network:
    driver: bridge
